### ISSUE TITLE
Repairs are no longer being found as the size of a dataset is increased

### ISSUE THREAD

**Issue by j-r77** [HoloClean/holoclean#41]
Hi,

I am trying to clean a few dirty rows with respect to 2 denial constraints:
t1&EQ(t1.Sex,"Female")&EQ(t1.Relationship,"Husband")
t1&EQ(t1.Sex,"Male")&EQ(t1.Relationship,"Wife")

When I use a small sample of my data (20 rows), I get the following correct repairs:
#(11, u'relationship', 'Husband', u'Husband')
**#(11, u'sex', 'Female', u'Male')**
#(4, u'relationship', 'Husband', u'Husband')
**#(4, u'sex', 'Female', u'Male')**

When I add some more rows, for example 1100, the values no longer change:
#(4, u'relationship', 'Husband', u'Husband')
#(4, u'sex', 'Female', u'Female')
#(11, u'relationship', 'Husband', u'Husband')
#(11, u'sex', 'Female', u'Female')
#(652, u'relationship', 'Husband', u'Husband')
#(652, u'sex', 'Female', u'Female')
#(689, u'relationship', 'Wife', u'Wife')
#(689, u'sex', 'Male', u'Male')
#(504, u'relationship', 'Husband', u'Husband')
#(504, u'sex', 'Female', u'Female')
#(26, u'relationship', 'Husband', u'Husband')
#(26, u'sex', 'Female', u'Female')
#(1084, u'relationship', 'Husband', u'Husband')
#(1084, u'sex', 'Female', u'Female')
#(703, u'relationship', 'Wife', u'Wife')
#(703, u'sex', 'Male', u'Male')

The same happens when I run on the full dataset, 48842 rows. The data is the same; e.g., the version with 20 rows just contains the first 20 rows from the full set.

My script is based on the example in tests/, and I use default settings (I tried some tweaking but this did not solve the issue)
Noisy cells are detected correctly and the generated possible domains contain multiple values

I do not understand why this happens, which problem or restriction prevents the repairs from happening on the larger versions of the dataset ...

Code and data can be found in my fork: https://github.com/j-r77/holoclean

**Comment by thodrek** [comment]
Hi, I would recommend using the HC version in Dev as we have fixed many issues there. Can you please let us if the error persists with the dev version? If so we would be happy to investigate.

**Comment by j-r77** [comment]
Hello,

I have just tried it in the latest dev version, but the issue persists. Values are repaired in the 20-tuple dataset, but the same values no longer change as a larger portion of the data is considered (and the new errors in the larger datasets are not repaired either).

**Comment by minafarid** [comment]
Hi @j-r77 I am currently working on reproducing and debugging this issue and will get back to you.

**Comment by fgeerts** [comment]
Hi @minafarid  Just wondering whether you managed to reproduce and debug the issue already? Thanks.

**Comment by thodrek** [comment]
Hi @fgeerts we are actively working on this issue. It is a bit more intricate than what it seems. This issue comes up because the only attributes that are strongly correlated in the Adult dataset are "relationship" and "sex", i.e., the ones present in your constraints (see attached image).

<img width="432" alt="screen shot 2018-12-17 at 11 42 45 am" src="https://user-images.githubusercontent.com/1043311/50105040-3174e000-01f1-11e9-86a1-29b782a0d948.png">

We are actively working on this issue and we will be getting back to you ASAP.

**Comment by richardwu** [comment]
Hi @j-r77:

We did some digging around and it seems that the issue lies in the use of `InitAttFeaturizer`. Because of how we currently do weak supervision, our `InitAttFeaturizer` feature weights actually blows up and will assign to much emphasis on the initial values which causes no repairs to occur.

If you pass in the keyword argument `learnable=False`, you should be able to see better results. We've recently tweaked how we do weak supervision in #43 such that `InitAttFeaturizer` behaves as intended. 

That being said with this specific dataset as @thodrek pointed out, since there are so few correlated attributes weak supervision fails to assign confident weak labels and results in the prior behaviour.

In this case Holoclean actually prefers _not_ to repair any cell as demonstrated because it is unconfident that any repairs are correct due to the lack of correlations.

Hope that helps.

**Comment by fgeerts** [comment]
Hi Richard,

Thanks for looking further into this. We’ll take a closer look
at this InitAttFeaturizer. Of course, it makes sense not to repair
if no strong signals are present. Thanks again,

-Floris
