### ISSUE TITLE
Correlation for categorical columns

### ISSUE THREAD

**Issue by deepakrajwani** [HoloClean/holoclean#79]
Hi

It was trying holoclean on some geographical dataset, which has columns like state-code,  state name and zip-code. I wrote rule "if two records have same state-code, then state name should be same".

But it was not at all correcting any records. Then i saw the correlation between state-code and state name, which was less than the default threshold used for holoclean (0.1), thus no repair was made.

To find correlation between categorical columns, holoclean does label encoding first for these columns and then checks for correlation, but I believe label encoding is not a good measure to calculate correlation between two categorical columns. We can say that state-code and state-name are correlated columns, but label encoding is not efficient to tell that.

I tried using statistical test like chi-square, and it gave me a good correlation between the state code and state name, thus errors were corrected.

I have two questions to ask:
1) Was there a specific reason of using label encoding to find correlation between two categorical columns ? 
2) Since repairs are done only on columns which are mentioned in rules, then how holoclean is better than a rule based approach. We can simply write code to correct errors for two columns, which says if two state code are same, then state names should be same (considering concept of minimality).

**Comment by richardwu** [comment]
Hi @deepakrajwani, sorry for the late reply but hopefully this addresses your questions:

1. We realized that the current implementation of correlation is incorrect since we are dealing with categorical values. We've implemented a correct "correlation" for categorical values using a (normalized) conditional entropy measure in the `dev` branch:
https://github.com/HoloClean/holoclean/blob/6db22a6d991e1eb89fa609dff581fd92ca660cc9/domain/domain.py#L62-L107

2. Repairs are done on cells that are detected with errors. Error detection in the current state only marks cells as potentially erroneous if they violate "rules" (denial constraints) and values that are NULL/empty. A rule-based approach using minimality may work in the simple case where we have an FD, but it is unclear how minimality would work with more complicated constraints with inequalities. Holoclean tries to address this in general with denial constraints and instead of explicit minimality repairing it learns the best repair based on the statistical properties of the data.

I would recommend you use more developed `dev` branch for now.
